# Generated by Django 4.1.5 on 2023-04-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='product', max_length=1000),
        ),
    ]
